
server:
  port: 
    8081
    
spring:
  data:
    mongodb:
#      port: 
#        27017
      database: 
        CarsEmbeddedDB
  mongodb:
    embedded:
      version: 
        5.0.0
#        4.4.6
#        4.0.2